name: Run deteKT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Running detekt
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-detekt-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-detekt-
      # when running detekt with type resolution, we need to have all project modules compiled too
      - name: running deteKT
        run: mvn -B compile dependency:build-classpath@detekt detekt:check@detekt -DskipPluginMarker
