name: Run diKTat from release version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          # set this to 0 to fetch all tags too and be able to use them later
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-diktat-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-diktat-
      - name: Substitute diktat config with the one from the latest release
        # fixme: can be done from the fetched repo without additional network request
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          DIKTAT_CONFIG=diktat-analysis.yml
          wget -O $DIKTAT_CONFIG https://raw.githubusercontent.com/cqfn/diKTat/$LATEST_TAG/$DIKTAT_CONFIG
      - name: Run diktat via maven plugin
        run: mvn -B diktat:check@diktat -DskipPluginMarker
