name: Run diKTat (release)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          # set this to 0 to fetch all tags too and be able to use them later
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Retrieve Kotlin version
        run: |
          kv=$(cat gradle/libs.versions.toml | grep '^kotlin =' | awk -F'[=]' '{print $2}' | tr -d '" ')
          echo KOTLIN_VERSION=$kv >> $GITHUB_ENV
      - name: Cache konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan-${{ env.KOTLIN_VERSION }}
      - name: Substitute diktat config with the one from the latest release
        # fixme: can be done from the fetched repo without additional network request
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          DIKTAT_CONFIG=diktat-analysis.yml
          wget -O $DIKTAT_CONFIG https://raw.githubusercontent.com/saveourtool/diKTat/$LATEST_TAG/$DIKTAT_CONFIG
      - name: Run diktat via gradle plugin
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          arguments: |
            :diktatCheck
            --scan
            --build-cache
