name: Run diKTat from snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diktat_snapshot_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository (shared with regular CI build)
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-build
      - name: Set version
        # Set project version which will then be used to run diktat from local maven repo.
        # Base version is stored in env variable for later usage.
        # Note: maven-help-plugin requires non-interactive mode (do not add -B flag).
        run: |
          snapshot_version=$(printf 'VERSION=${project.version}\n0\n' | mvn help:evaluate | grep '^VERSION' | cut -d= -f2)
          base_version=${snapshot_version%-SNAPSHOT}
          echo "BASE_VERSION=$base_version" >> $GITHUB_ENV
          mvn -B versions:set -DnewVersion=$base_version-pre
      - name: Build and install
        # install diktat with version 'base_version-pre' to local maven repo
        run: mvn -B clean install -DskipTests=true --projects diktat-maven-plugin --also-make
      - name: Revert project version and set proper version for diktat check
        # revert project version to avoid cycle dependency
        # set diktat version in plugin dependencies to the version which was built in the previous step
        run: |
          mvn -B versions:set -DnewVersion=${{ env.BASE_VERSION }}-SNAPSHOT
          mvn -B versions:set-property -Dproperty=diktat-check.version -DnewVersion=${{ env.BASE_VERSION }}-pre
      - name: Run diktat snapshot via ktlint
        run: |
          mvn -B diktat:check@diktat --pl diktat-common || echo "LintErrors encountered"
          mvn -B diktat:check@diktat --pl diktat-maven-plugin || echo "LintErrors encountered"
          mvn -B diktat:check@diktat --pl diktat-test-framework || echo "LintErrors encountered"
          mvn -B diktat:check@diktat --pl diktat-rules
