name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

#       - name: Run diKTat from cli
#         run: ./ktlint -R diktat.jar "dir/your/dir/**/*.kt"

      - name: Run diKTat from gradle
        run: gradle diktatCheck
        
      - name: Run diKTat from maven
        run: mvn antrun:run@diktat
