name: Run functional tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DIKTAT_VERSION: 0.1.7
  KTLINT_VERSION: 0.39.0
  GRADLE_OPTS: -Dorg.gradle.daemon=false  # to speed up gradle run

jobs:
  run_diktat_from_CLI:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Setup environment
        run: |
          cat pom.xml | grep "<diktat-check.version>.*</diktat-check.version>" | head -1 |awk -F'[><]' '{ENVIRON[DIKTAT_VERSION]=$3 ; print ENVIRON[DIKTAT_VERSION]}'
          cat pom.xml | grep "<ktlint.version>.*</ktlint.version>" | head -1 |awk -F'[><]' '{ENVIRON[KTLINT_VERSION]=$3 ; print ENVIRON[KTLINT_VERSION]}'
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/$KTLINT_VERSION/ktlint && chmod a+x ktlint
          curl -sSLO https://github.com/cqfn/diKTat/releases/download/v$DIKTAT_VERSION/diktat-$DIKTAT_VERSION.jar

      - name: Copy diktat-analysis.yml from release
        run: |
          unzip -q -d tmp diktat-$DIKTAT_VERSION.jar
          DIKTAT_CONFIG=diktat-analysis.yml
          find tmp -name $DIKTAT_CONFIG -exec cp "{}" . \;

      - name: Run diKTat from cli
        continue-on-error: true
        run: |
          ./ktlint -R diktat-$DIKTAT_VERSION.jar "examples/maven/src/main/kotlin/Test.kt" &> out

      - name: Check output
        id: cli-check
        run: |
          cat out
          grep -E "\[VARIABLE_NAME_INCORRECT_FORMAT\]" out

  run_diktat_from_gradle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Setup environment
        run: |
          cat pom.xml | grep "<diktat-check.version>.*</diktat-check.version>" | head -1 |awk -F'[><]' '{ENVIRON[DIKTAT_VERSION]=$3 ; print ENVIRON[DIKTAT_VERSION]}'
          curl -sSLO https://github.com/cqfn/diKTat/releases/download/v$DIKTAT_VERSION/diktat-$DIKTAT_VERSION.jar
          unzip -q -d tmp diktat-$DIKTAT_VERSION.jar
          DIKTAT_CONFIG=diktat-analysis.yml
          find tmp -name $DIKTAT_CONFIG -exec cp "{}" . \;

      - name: Run diKTat from gradle kotlin DSL
        continue-on-error: true
        working-directory: ./examples/gradle-kotlin-dsl
        run: |
          gradle diktatCheck &> out

      - name: Check gradle from kotlin DSL
        working-directory: ./examples/gradle-kotlin-dsl
        run: |
          cat out
          grep -E "\[VARIABLE_NAME_INCORRECT_FORMAT\]" out

      - name: Run diKTat from gradle groovy DSL
        continue-on-error: true
        working-directory: ./examples/gradle-groovy-dsl
        run: |
          gradle diktatCheck &> out

      - name: Check gradle from groovy DSL
        working-directory: ./examples/gradle-groovy-dsl
        run: |
          cat out
          grep -E "\[VARIABLE_NAME_INCORRECT_FORMAT\]" out

  run_diktat_from_maven:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Setup environment
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              Invoke-WebRequest -Uri https://github.com/cqfn/diKTat/releases/download/v$DIKTAT_VERSION/diktat-$DIKTAT_VERSION.jar -OutFile diktat-$DIKTAT_VERSION.jar
          else
              cat pom.xml | grep "<diktat-check.version>.*</diktat-check.version>" | head -1 |awk -F'[><]' '{ENVIRON[DIKTAT_VERSION]=$3 ; print ENVIRON[DIKTAT_VERSION]}'
              curl -sSLO https://github.com/cqfn/diKTat/releases/download/v$DIKTAT_VERSION/diktat-$DIKTAT_VERSION.jar
              unzip -q -d tmp diktat-$DIKTAT_VERSION.jar
              DIKTAT_CONFIG=diktat-analysis.yml
              find tmp -name $DIKTAT_CONFIG -exec cp "{}" . \;
          fi
        shell: bash

      - name: Run diKTat from maven
        working-directory: ./examples/maven
        continue-on-error: true
        run: mvn -B diktat:check &> out

      - name: Check maven
        working-directory: ./examples/maven
        run: |
          cat out
          grep -E "\[VARIABLE_NAME_INCORRECT_FORMAT\]" out
