name: Create diKTat release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-build-
      - name: Setup environment
        env:
          DIKTAT_GPG_PUB: ${{ secrets.DIKTAT_PGP_PUB }}
          DIKTAT_GPG_SEC: ${{ secrets.DIKTAT_PGP_SEC }}
        # Note: maven-help-plugin requires non-interactive mode (do not add -B flag).
        run: |
          previous_version=$(printf 'VERSION=${diktat-check.version}\n0\n' | mvn help:evaluate | grep '^VERSION' | cut -d= -f2)
          echo "PREVIOUS_VERSION=$previous_version" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#'refs/tags/v'}" >> $GITHUB_ENV
          echo "$DIKTAT_GPG_PUB" > ~/diktat.pubring.gpg
          echo "$DIKTAT_GPG_SEC" > ~/diktat.secring.gpg
          gpg --import ~/diktat.pubring.gpg
          gpg --batch --import ~/diktat.secring.gpg  # --batch suppresses intercatively asking passphrase
      - name: Set version
        run: mvn -B versions:set -DnewVersion=${{ env.RELEASE_VERSION }} versions:commit
      - name: Create settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [
              { "id": "ossrh", "username": "${{ secrets.SONATYPE_USER }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" },
              { "id": "gpg.passphrase", "passphrase": "${{ secrets.DIKTAT_GPG_PASS }}" },
              { "id": "kotlin-maven-plugin-tools", "username": "${{github.actor}}", "password": "${{ secrets.GITHUB_TOKEN }}" }
            ]
        # Runs tests, incl. smoke tests (using a fat JAR built from the
        # "diktat-ruleset" module). The fat JAR is also used later during the
        # "upload-release-asset" step (see below).
      - name: Run tests
        run: mvn -B clean install
        # "diktat-ruleset" is a module that creates a fat JAR, which is,
        # obviously, never released. Since we *do need* this fat JAR in order to
        # run smoke tests, we *skip tests entirely* in this step.
      - name: Deploy artifacts (skipping the clean, test, and verify phases)
        run: mvn -B deploy -Prelease --projects "!diktat-ruleset" -DskipTests=true
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: Upload assets to github releases
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./diktat-ruleset/target/diktat-${{ env.RELEASE_VERSION }}.jar
          asset_name: diktat-${{ env.RELEASE_VERSION }}.jar
          asset_content_type: application/zip
      - name: Update versions in pom.xml and documentation, update examples
        id: update-versions
        run: |
          mvn -B versions:set -DnextSnapshot=true -DprocessAllModules=true versions:commit
          mvn versions:set-property -Dproperty=diktat-check.version -DnewVersion=${{ env.RELEASE_VERSION }}
          sed -i "s/$PREVIOUS_VERSION/$RELEASE_VERSION/g" README.md || echo "File README.md hasn't been updated!"
          for file in examples/{maven/pom.xml,gradle-groovy-dsl/build.gradle,{gradle-kotlin-dsl,gradle-kotlin-dsl-multiproject}/build.gradle.kts}
          do
            sed -i "s/$PREVIOUS_VERSION/$RELEASE_VERSION/g" $file || echo "File $file hasn't been updated!"
            cp diktat-rules/src/main/resources/diktat-analysis.yml $(dirname $file)
          done
          next_snapshot_version=$(printf 'VERSION=${project.version}\n0\n' | mvn help:evaluate | grep '^VERSION' | cut -d= -f2)
          # Update the version in `examples/maven/pom.xml`
          # (which is not a part of the multi-module project).
          for file in examples/maven/pom.xml
          do
            sed -i "s|\(<version>\)[[:digit:]]\(\.[[:digit:]]\)\+-SNAPSHOT\(</version>\)|\1${next_snapshot_version}\3|g" "${file}" || echo "File ${file} hasn't been updated (2nd sed pass)"
          done
          echo "version=$next_snapshot_version" > info/buildSrc/gradle.properties
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          author: GitHub <noreply@github.com>
          commit-message: Prepare next development iteration after release ${{ env.RELEASE_VERSION }}
          branch: infra/diktat-version-update-to-${{ env.RELEASE_VERSION }}
          title: Update versions in pom.xml and documentation after ${{ env.RELEASE_VERSION }} release
          body: |
            * Versions are updated in pom.xml, README.md and in examples
            * Current project version is incremented to the next snapshot
          base: master
